server:
  applicationConnectors:
    - type: http
      port: 8088
  adminConnectors:
    - type: http
      port: 9889
mongoDBConnection:
  credentials:
    username: "danielsan"
    password: "danielsan"
  seeds:
    - host: "localhost"
      port: 27017
  database: "dw_usuario"